codigo = input("Ingrese el código del equipo: ")
marca = input("Ingrese la marca: ")
procesador = input("Ingrese el procesador: ")
ram = input("Ingrese la memoria RAM: ")
disco = input("Ingrese la capacidad del disco: ")
so = input("Ingrese el sistema operativo: ")
estado = input("Ingrese el estado del equipo: ")

print("\n--- FICHA TÉCNICA DEL EQUIPO ---")
print("Código:", codigo)
print("Marca:", marca)
print("Procesador:", procesador)
print("Memoria RAM:", ram)
print("Capacidad de Disco:", disco)
print("Sistema Operativo:", so)
print("Estado:", estado)